// config.bin - 14:02:17 04/23/25, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class Larger_ACE_Nightvision_Border {
		units[] = {};
		weapons[] = {};
		requiredAddons[] = {"ace_nightvision"};
		version = 1.0.1;
		author = "D. Wolfe";
		authorUrl = "https://steamcommunity.com/id/redthirten/";
	};
};

class CfgWeapons {
	class Binocular;	// External class reference
	
	class NVGoggles : Binocular {
		ace_nightvision_border = "\Larger_ACE_Nightvision_Border\data\nvg_mask_binos_4096_2x.paa";
	};
	
	class O_NVGoggles_hex_F : NVGoggles {
		ace_nightvision_border = "\Larger_ACE_Nightvision_Border\data\nvg_mask_quad_4096_2x.paa";
	};
	
	class ACE_NVG_Biocular : NVGoggles {
		ace_nightvision_border = "\Larger_ACE_Nightvision_Border\data\nvg_mask_4096_2x.paa";
	};
	
	class ACE_NVG_Monocular : NVGoggles {
		ace_nightvision_border = "\Larger_ACE_Nightvision_Border\data\nvg_mask_4096_2x.paa";
	};
	
	class ACE_NVG_Binocular : NVGoggles {
		ace_nightvision_border = "\Larger_ACE_Nightvision_Border\data\nvg_mask_binos_4096_2x.paa";
	};
	
	class ACE_NVG_Quadocular : NVGoggles {
		ace_nightvision_border = "\Larger_ACE_Nightvision_Border\data\nvg_mask_quad_4096_2x.paa";
	};
};

class cfgMods {
	author = "D. Wolfe";
	timepacked = 1605796945;
};
